# Generated by Django 2.1.5 on 2021-06-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
