#!/usr/bin/env bash
flask db upgrade
if [ "$FLASK_ENV" = "development" ] || [ "$FLASK_ENV" = "testing" ]
then
  flask run --host=0.0.0.0 --port=8000
else
  waitress-serve --port=8000 --call 'app:create_app' 
fi