#!/usr/bin/env bash

# Running the Flask application
if [ "$ENV" = "development" ] || [ "$ENV" = "testing" ]
then  
  python manage.py runserver 0.0.0.0:8000
else
  python manage.py runserver 0.0.0.0:8000
fi